import { adminPage, dir } from "./admin-session.tmp.mjs";
const { browser, page, errors } = await adminPage();
await page.goto("http://localhost:3000/admin/reservations/nouvelle");
await page.getByRole("combobox", { name: /^Bien/ }).selectOption({ label: "Démo · Appartement Talence (B-010)" });
await page.getByLabel("Plateforme", { exact: true }).selectOption("booking");
await page.getByLabel(/^Arrivée/).fill("2026-11-10");
await page.getByLabel(/^Départ/).fill("2026-11-13");
await page.getByLabel("Prix des nuitées (€)").fill("300");
await page.getByLabel("… ou en % des nuitées").fill("15");
await page.getByLabel("Frais de ménage perçus (€)").fill("60");
await page.getByLabel("Prénom").first().fill("Test");
await page.getByRole("textbox", { name: "Nom", exact: true }).fill("Parcours");
console.log(await page.locator("[aria-live=polite] dl").innerText());
await page.getByRole("button", { name: "Enregistrer la réservation" }).click();
await page.waitForURL(/reservations\/[0-9a-f-]{36}/);
await page.screenshot({ path: `${dir}/booking.png`, fullPage: true });
console.log(page.url());
console.log(await page.locator("#montants").innerText());
console.log(await page.locator("#taches").innerText());
console.log(errors.length ? errors : "no errors");
await browser.close();
