import { chromium } from "playwright-core";
import { generate } from "otplib";
import fs from "fs";
const [,, path = "/admin", out = "shot", width = "1440", height = "900"] = process.argv;
const dir = "/tmp/claude-0/-home-user-Comme-la-maison/f1ce638e-0329-54b8-846d-ed5ae9b913c5/scratchpad";
const secret = fs.readFileSync(`${dir}/totp-secret.txt`, "utf8").trim();
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const context = await browser.newContext({ viewport: { width: Number(width), height: Number(height) } });
const page = await context.newPage();
const errors = [];
page.on("pageerror", (e) => errors.push(String(e)));
await page.goto("http://localhost:3000/connexion");
await page.getByRole("textbox", { name: /Adresse email/ }).first().fill("baptiste.dev@example.com");
await page.getByLabel(/Mot de passe/).fill("motdepasse-dev-2026");
await page.getByRole("button", { name: "Se connecter" }).click();
await page.waitForURL(/double-authentification/);
await page.getByLabel(/Code à 6 chiffres/).fill(await generate({ secret }));
await page.getByRole("button", { name: "Valider" }).click();
await page.waitForURL("http://localhost:3000/admin");
await page.goto(`http://localhost:3000${path}`);
await page.waitForLoadState("networkidle");
await page.screenshot({ path: `${dir}/${out}.png`, fullPage: true });
console.log(page.url(), errors.length ? errors : "no errors");
await browser.close();
