import { chromium } from "playwright-core";
const dir = "/tmp/claude-0/-home-user-Comme-la-maison/f1ce638e-0329-54b8-846d-ed5ae9b913c5/scratchpad";
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
const page = await context.newPage();
const errors = [];
page.on("pageerror", (e) => errors.push(String(e)));
await page.goto("http://localhost:3000/connexion");
await page.getByRole("textbox", { name: /Adresse email/ }).first().fill("agent.dev@example.com");
await page.getByLabel(/Mot de passe/).fill("motdepasse-dev-2026");
await page.getByRole("button", { name: "Se connecter" }).click();
await page.waitForURL(/\/staff/);
await page.getByRole("link", { name: /Ménage · Démo · T2 Chartrons/ }).first().click();
await page.waitForURL(/\/staff\/taches\//);
console.log("codes:", (await page.locator("#acces").innerText()).replace(/\n+/g, " | "));
await page.getByRole("button", { name: "Commencer" }).click();
await page.getByText("Tâche commencée.").waitFor();
await page.setInputFiles("input[type=file]", `${dir}/photo.png`);
await page.getByRole("button", { name: "Envoyer" }).click();
await page.getByText(/1 fichier\(s\) enregistré\(s\)/).waitFor({ timeout: 30000 });
console.log("photo ok");
const boxes = page.locator("#liste input[type=checkbox][name^=item-]");
const n = await boxes.count();
for (let i = 0; i < n; i++) await boxes.nth(i).check();
await page.getByLabel("Notes pour l’équipe").fill("RAS, un rouleau de papier toilette à racheter.");
await page.getByRole("button", { name: "Terminer la tâche" }).click();
await page.getByText(/Tâche terminée/).waitFor();
await page.reload();
await page.screenshot({ path: `${dir}/staff-task.png`, fullPage: true });
console.log("status:", await page.locator("header").first().innerText());
console.log(errors.length ? errors : "no errors");
await browser.close();
