import { adminPage, dir } from "./admin-session.tmp.mjs";
const { browser, page, errors } = await adminPage();
await page.goto("http://localhost:3000/admin/synchronisation");
await page.getByRole("button", { name: "Tout synchroniser maintenant" }).click();
await page.getByRole("alert").or(page.getByRole("status").filter({ hasText: "calendrier" })).first().waitFor({ timeout: 30000 });
console.log(await page.locator("form [role=alert], form [role=status]").allInnerTexts());
await page.reload();
await page.screenshot({ path: `${dir}/sync.png`, fullPage: true });
console.log(await page.locator("#a-completer").innerText());
console.log(errors.length ? errors : "no errors");
await browser.close();
