/**
 * Photos des adresses du guide voyageurs (fichiers dans public/guide/lieux/).
 *
 * Généré le 27/09/2026 : pour chaque lieu, une photographie du lieu réel, choisie
 * à la main sur Wikimedia Commons, sous licence libre (CC0, domaine public,
 * CC BY ou CC BY-SA). L'auteur et la licence sont affichés sur la fiche de l'adresse,
 * avec un lien vers la page d'origine. Jamais d'image générée ni d'image « d'ambiance »
 * qui ne montre pas le lieu : une adresse sans photo garde l'illustration de la marque.
 *
 * Une photo ajoutée depuis le back-office (Guide voyageurs) remplace celle-ci.
 * Recadrage commun : 3:2, 1050 × 700 px, WebP.
 */

export type BundledPlacePhoto = { src: string; alt: string; credit: string; sourceUrl: string };

export const placePhotos: Record<string, BundledPlacePhoto> = {
  "abbaye-la-sauve-majeure": {
    src: "/guide/lieux/abbaye-la-sauve-majeure.webp",
    alt: "Les vestiges du cloître de l’abbaye de La Sauve-Majeure",
    credit: "William Ellison, CC BY-SA 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Abbaye_de_la_Sauve-Majeure_clo%C3%AEtre.JPG",
  },
  "arcachon": {
    src: "/guide/lieux/arcachon.webp",
    alt: "Une villa de la Ville d’Hiver, à Arcachon",
    credit: "PA, CC BY-SA 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Arcachon_-_Villa_Fragonard.jpg",
  },
  "arkea-arena": {
    src: "/guide/lieux/arkea-arena.webp",
    alt: "La façade blanche de l’Arkéa Arena",
    credit: "Marcel Roblin, CC BY-SA 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Arkea_Arena.jpg",
  },
  "baillardran": {
    src: "/guide/lieux/baillardran.webp",
    alt: "Coffrets de canelés Baillardran",
    credit: "DimiTalen, CC0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Boxes_of_Baillardran_canel%C3%A9s,_Bordeaux,_2015.jpg",
  },
  "basilique-saint-michel": {
    src: "/guide/lieux/basilique-saint-michel.webp",
    alt: "La flèche Saint-Michel et la basilique",
    credit: "Jean-Christophe BENOIST, CC BY 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bordeaux_-_Basilique_Saint-Michel_-_Vue_g%C3%A9n%C3%A9rale.jpg",
  },
  "basilique-saint-seurin": {
    src: "/guide/lieux/basilique-saint-seurin.webp",
    alt: "Façade de la basilique Saint-Seurin",
    credit: "JPRoche, CC BY-SA 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Saint-Seurin_7SC1988EC.jpg",
  },
  "bassins-des-lumieres": {
    src: "/guide/lieux/bassins-des-lumieres.webp",
    alt: "Exposition numérique projetée sur les murs de l’ancienne base sous-marine",
    credit: "Immersivearteditor, CC BY-SA 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Gustav_Klimt_-_d%27or_et_du_couleurs.jpg",
  },
  "bat3": {
    src: "/guide/lieux/bat3.webp",
    alt: "Une navette fluviale sur la Garonne",
    credit: "Ardfern, CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:BatCub,_Bordeaux,_July_2014.JPG",
  },
  "biscarrosse-plage": {
    src: "/guide/lieux/biscarrosse-plage.webp",
    alt: "Le front de mer de Biscarrosse-Plage",
    credit: "Echtner, CC BY 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Biscarrosse_Plage_2.JPG",
  },
  "bois-de-bordeaux": {
    src: "/guide/lieux/bois-de-bordeaux.webp",
    alt: "Le lac du parc floral, dans le Bois de Bordeaux",
    credit: "Michel BUZE, CC BY-SA 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Parc_floral_de_Bordeaux_3280.jpg",
  },
  "bouliac": {
    src: "/guide/lieux/bouliac.webp",
    alt: "L’église Saint-Siméon de Bouliac",
    credit: "William Ellison, CC BY-SA 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bouliac_%C3%A9glise_Saint-Sim%C3%A9on_1.JPG",
  },
  "bourg": {
    src: "/guide/lieux/bourg.webp",
    alt: "Bourg, ses remparts et le bord de la Dordogne",
    credit: "Michel Reza, CC BY-SA 2.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bourg-sur-Gironde2.jpg",
  },
  "cap-ferret": {
    src: "/guide/lieux/cap-ferret.webp",
    alt: "Le phare du Cap Ferret au-dessus du bassin",
    credit: "Rundvald, CC BY-SA 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:CapFerret-phare%2Bplage1-byRundvald.jpg",
  },
  "cap-sciences": {
    src: "/guide/lieux/cap-sciences.webp",
    alt: "Façade vitrée de Cap Sciences, sur les quais",
    credit: "Ardfern, CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cap_Sciences,_Bordeaux,_July_2014.JPG",
  },
  "capc": {
    src: "/guide/lieux/capc.webp",
    alt: "L’entrepôt Lainé, qui abrite le CAPC",
    credit: "Ardfern, CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:CAPC,_Bordeaux,_July_2014_(09).JPG",
  },
  "carcans-plage": {
    src: "/guide/lieux/carcans-plage.webp",
    alt: "La dune et l’océan à Carcans-Plage",
    credit: "Michel VENOT, CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Carcans_plage.jpg",
  },
  "cathedrale-saint-andre": {
    src: "/guide/lieux/cathedrale-saint-andre.webp",
    alt: "La façade gothique de la cathédrale Saint-André",
    credit: "Chabe01, CC BY-SA 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cath%C3%A9drale_St_Andr%C3%A9_Bordeaux_2.jpg",
  },
  "cercle-guiraud": {
    src: "/guide/lieux/cercle-guiraud.webp",
    alt: "Le château Guiraud, à Sauternes",
    credit: "Henry Salomé, CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sauternes_Ch%C3%A2teau_Guiraud_03.jpg",
  },
  "chartrons": {
    src: "/guide/lieux/chartrons.webp",
    alt: "La rue Notre-Dame, dans le quartier des Chartrons",
    credit: "Ardfern, CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Rue_Notre-Dame,_Bordeaux,_July_2014_(05).JPG",
  },
  "chateau-de-cadillac": {
    src: "/guide/lieux/chateau-de-cadillac.webp",
    alt: "Le château des ducs d’Épernon, à Cadillac",
    credit: "Fabien.lotte, CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ch%C3%A2teau_des_ducs_d%27%C3%A9pernons_-_Cadillac.jpg",
  },
  "chateau-de-roquetaillade": {
    src: "/guide/lieux/chateau-de-roquetaillade.webp",
    alt: "Le château de Roquetaillade et ses tours",
    credit: "Florent Pécassou, CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ch%C3%A2teau_de_Roquetaillade_(Gironde,_France).JPG",
  },
  "chateau-lynch-bages": {
    src: "/guide/lieux/chateau-lynch-bages.webp",
    alt: "Cordeillan-Bages, dans le village de Bages",
    credit: "ryanovineyards, CC BY-SA 2.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Le_Relais_%26_Ch%C3%A2teaux_Cordeillan-Bages.jpg",
  },
  "chateau-pape-clement": {
    src: "/guide/lieux/chateau-pape-clement.webp",
    alt: "Les chais du château Pape Clément",
    credit: "Kassander der Minoer at German Wikipedia, CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:PapeClement01.jpg",
  },
  "chez-jean-mi": {
    src: "/guide/lieux/chez-jean-mi.webp",
    alt: "Huîtres servies au marché des Capucins",
    credit: "Benreis, CC BY-SA 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Oysters_March%C3%A9_des_Capucins_Bordeaux_(1).jpg",
  },
  "cinema-utopia": {
    src: "/guide/lieux/cinema-utopia.webp",
    alt: "Le cinéma Utopia, installé dans l’ancienne église Saint-Siméon",
    credit: "Marc Ryckaert (MJJR), CC BY 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bordeaux_Place_Camille_Jullian_R01.jpg",
  },
  "citadelle-de-blaye": {
    src: "/guide/lieux/citadelle-de-blaye.webp",
    alt: "Les remparts de la citadelle de Blaye au-dessus de l’estuaire",
    credit: "Pinpin, CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:France_-_Blaye_-_La_Gironde_depuis_la_citadelle.jpg",
  },
  "cite-du-vin": {
    src: "/guide/lieux/cite-du-vin.webp",
    alt: "Le bâtiment de la Cité du Vin au bord de la Garonne",
    credit: "ANAKA, CC BY 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%C2%A9ANAKA-2024-HD-citeExt2.jpg",
  },
  "darwin": {
    src: "/guide/lieux/darwin.webp",
    alt: "Les bâtiments de l’ancienne caserne Niel, à Darwin",
    credit: "A1AA1A, CC BY-SA 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Darwin_-_Magasin_g%C3%A9n%C3%A9ral.jpg",
  },
  "dune-du-pilat": {
    src: "/guide/lieux/dune-du-pilat.webp",
    alt: "Le sable de la dune du Pilat face à l’océan",
    credit: "Rundvald, CC BY-SA 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Dune-du-Pilat%2BAtlantique-byMmeRundvald.jpg",
  },
  "galerie-bordelaise": {
    src: "/guide/lieux/galerie-bordelaise.webp",
    alt: "L’allée couverte de la Galerie Bordelaise",
    credit: "Langladure, CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bordeaux_Galerie_Bordelaise17.JPG",
  },
  "gina-rooftop": {
    src: "/guide/lieux/gina-rooftop.webp",
    alt: "Les bassins à flot, au pied de l’hôtel Renaissance",
    credit: "Somniatruites, CC BY-SA 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bassins_%C3%A0_flot,_Bordeaux.jpg",
  },
  "grand-theatre": {
    src: "/guide/lieux/grand-theatre.webp",
    alt: "La colonnade du Grand Théâtre, place de la Comédie",
    credit: "Marc Ryckaert (MJJR), CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bordeaux_Grand_Th%C3%A9%C3%A2tre_R01.jpg",
  },
  "grosse-cloche": {
    src: "/guide/lieux/grosse-cloche.webp",
    alt: "La Grosse Cloche, ancienne porte de ville, rue Saint-James",
    credit: "Grand Parc - Bordeaux, France from France, CC BY 2.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bordeaux_-_La_Grosse_Cloche-cr.jpg",
  },
  "ile-aux-oiseaux": {
    src: "/guide/lieux/ile-aux-oiseaux.webp",
    alt: "Les cabanes tchanquées de l’île aux Oiseaux",
    credit: "Karine Deydier, CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bassin_d%27Arcachon_-_Cabanes_tchanqu%C3%A9es.jpg",
  },
  "jardin-botanique-bastide": {
    src: "/guide/lieux/jardin-botanique-bastide.webp",
    alt: "Le plan d’eau du jardin botanique de la Bastide",
    credit: "DaveM93, CC BY-SA 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Plan_d%27eau_-_Jardin_Botanique_de_Bordeaux.jpg",
  },
  "jardin-public": {
    src: "/guide/lieux/jardin-public.webp",
    alt: "Le pont et la rivière du Jardin Public",
    credit: "Marc Ryckaert (MJJR), CC BY 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bordeaux_Jardin_Public_R02.jpg",
  },
  "l-intendant": {
    src: "/guide/lieux/l-intendant.webp",
    alt: "Les allées de Tourny, où se trouve L’Intendant",
    credit: "Bordeaux at German Wikipedia, CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bordeaux_Allees_Tourny.JPG",
  },
  "la-tupina": {
    src: "/guide/lieux/la-tupina.webp",
    alt: "La cheminée où grillent les viandes, à La Tupina",
    credit: "Guallendra, CC BY-SA 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bordeaux_La_Tupina_chemin%C3%A9e.JPG",
  },
  "lacanau-ocean": {
    src: "/guide/lieux/lacanau-ocean.webp",
    alt: "La plage et la dune de Lacanau-Océan",
    credit: "Azotte, CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Lacanau-ocean_plage_2013(05).JPG",
  },
  "le-7": {
    src: "/guide/lieux/le-7.webp",
    alt: "Vue sur la Garonne et Bordeaux depuis la Cité du Vin",
    credit: "Zairon, CC BY-SA 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bordeaux_Cit%C3%A9_du_Vin_Vue_panoramique_2.jpg",
  },
  "le-porge-ocean": {
    src: "/guide/lieux/le-porge-ocean.webp",
    alt: "Coucher de soleil sur la plage du Porge",
    credit: "Michel BUZE, CC BY-SA 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Porge_Ocean_Coucher_de_soleil.JPG",
  },
  "madd": {
    src: "/guide/lieux/madd.webp",
    alt: "L’hôtel de Lalande, qui abrite le madd",
    credit: "Dark Attsios, CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mus%C3%A9e_des_arts_d%C3%A9coratifs_de_Bordeaux.jpg",
  },
  "magasin-general": {
    src: "/guide/lieux/magasin-general.webp",
    alt: "La terrasse du Magasin Général, à Darwin",
    credit: "Jefunky, CC BY-SA 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Magasin_g%C3%A9n%C3%A9ral_de_l%27%C3%A9cosyst%C3%A8me_Darwin_%C3%A0_Bordeaux_(ancienne_caserne_Niel),_22_novembre_2021_(2).jpg",
  },
  "marche-des-capucins": {
    src: "/guide/lieux/marche-des-capucins.webp",
    alt: "Étals de fruits et légumes sous la halle du marché des Capucins",
    credit: "Benreis, CC BY-SA 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:March%C3%A9_des_Capucins_2024_(4).jpg",
  },
  "marche-des-chartrons": {
    src: "/guide/lieux/marche-des-chartrons.webp",
    alt: "La halle et la place du marché des Chartrons",
    credit: "Ardfern, CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Place_du_March%C3%A9_des_Chartrons,_Bordeaux,_July_2014_(02).JPG",
  },
  "miroir-d-eau": {
    src: "/guide/lieux/miroir-d-eau.webp",
    alt: "Le palais de la Bourse qui se reflète dans le Miroir d’eau",
    credit: "Léna, CC BY 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Miroir_d%27eau_Bordeaux_panorama.jpg",
  },
  "musee-d-aquitaine": {
    src: "/guide/lieux/musee-d-aquitaine.webp",
    alt: "Façade du musée d’Aquitaine, cours Pasteur",
    credit: "Tiraden, CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mus%C3%A9e_Aquitaine.JPG",
  },
  "musee-mer-marine": {
    src: "/guide/lieux/musee-mer-marine.webp",
    alt: "Sculpture de requin devant le musée Mer Marine",
    credit: "CGE, CC0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Requin_de_Philippe_Pasqua_-_1.jpg",
  },
  "museum-bordeaux": {
    src: "/guide/lieux/museum-bordeaux.webp",
    alt: "L’hôtel de Lisleferme, qui abrite le Muséum",
    credit: "Jefunky, CC BY-SA 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:H%C3%B4tel_de_Lisleferme,_Mus%C3%A9um_d%27histoire_naturelle_de_Bordeaux,_2019_-_1.jpg",
  },
  "night-beach": {
    src: "/guide/lieux/night-beach.webp",
    alt: "Le Grand Hôtel illuminé, vu depuis le Grand Théâtre",
    credit: "Grand Hôtel de Bordeaux & Spa, CC BY-SA 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Photo_facade_nuit_avec_2_statues.jpg",
  },
  "parc-bordelais": {
    src: "/guide/lieux/parc-bordelais.webp",
    alt: "Arbres aux couleurs d’automne au Parc Bordelais",
    credit: "Olivier Aumage, CC BY-SA 2.0 fr, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bordeaux_parc_bordelais_02.jpg",
  },
  "parc-de-l-ermitage": {
    src: "/guide/lieux/parc-de-l-ermitage.webp",
    alt: "Les falaises du parc de l’Ermitage, à Lormont",
    credit: "William Ellison, CC BY-SA 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Lormont_ermitage_zone_2.jpg",
  },
  "parc-de-majolan": {
    src: "/guide/lieux/parc-de-majolan.webp",
    alt: "Les grottes et le lac du parc de Majolan",
    credit: "Carolaidron, CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Majolan_2.JPG",
  },
  "phare-de-cordouan": {
    src: "/guide/lieux/phare-de-cordouan.webp",
    alt: "Le phare de Cordouan au milieu de l’estuaire",
    credit: "Rémih, CC BY-SA 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Phare_de_Cordouan_32.jpg",
  },
  "piste-roger-lapebie": {
    src: "/guide/lieux/piste-roger-lapebie.webp",
    alt: "La piste cyclable Roger-Lapébie, entre les arbres",
    credit: "Symac / Sylvain Machefert, CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Piste_cyclable_Roger_Lap%C3%A9bie.jpg",
  },
  "place-de-la-bourse": {
    src: "/guide/lieux/place-de-la-bourse.webp",
    alt: "La place de la Bourse et ses façades du XVIIIᵉ siècle",
    credit: "P. Hughes, CC BY 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bordeaux_-_Place_de_la_Bourse_10.jpg",
  },
  "place-de-la-victoire": {
    src: "/guide/lieux/place-de-la-victoire.webp",
    alt: "La porte d’Aquitaine, place de la Victoire",
    credit: "Patrick Despoix, CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:021_-_Place_de_la_Victoire_-_Bordeaux.jpg",
  },
  "place-des-quinconces": {
    src: "/guide/lieux/place-des-quinconces.webp",
    alt: "La fontaine du monument aux Girondins, esplanade des Quinconces",
    credit: "Romainbehar, CC0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bordeaux_-_Monument_aux_Girondins_-_Fontaine_du_Triomphe_de_la_R%C3%A9publique_01.jpg",
  },
  "plage-du-petit-nice": {
    src: "/guide/lieux/plage-du-petit-nice.webp",
    alt: "La plage surveillée du Petit Nice",
    credit: "Pline, CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Baignade_surveill%C3%A9e_a_la_TesteDSC_0158.JPG",
  },
  "pont-chaban-delmas": {
    src: "/guide/lieux/pont-chaban-delmas.webp",
    alt: "Le pont Jacques Chaban-Delmas, tablier levé",
    credit: "Prométhée33, CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pont_Jacques-Chaban-Delmas_lev%C3%A9_03.JPG",
  },
  "pont-de-pierre": {
    src: "/guide/lieux/pont-de-pierre.webp",
    alt: "Le pont de pierre et ses arches au-dessus de la Garonne",
    credit: "Patrick Despoix, CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:151_-_Le_Pont_de_Pierre_-_Bordeaux.jpg",
  },
  "porte-cailhau": {
    src: "/guide/lieux/porte-cailhau.webp",
    alt: "La porte Cailhau et ses toits pointus",
    credit: "Marc Ryckaert (MJJR), CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bordeaux_Porte_Cailhau_R02.jpg",
  },
  "pressoir-d-argent": {
    src: "/guide/lieux/pressoir-d-argent.webp",
    alt: "La façade du Grand Hôtel de Bordeaux, place de la Comédie",
    credit: "P. Hughes, CC BY 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bordeaux_-_Grand_Hotel.jpg",
  },
  "puces-saint-michel": {
    src: "/guide/lieux/puces-saint-michel.webp",
    alt: "La place Canteloup, dans le quartier Saint-Michel",
    credit: "Zairon, CC BY-SA 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bordeaux_Place_Canteloup.jpg",
  },
  "quais-de-bordeaux": {
    src: "/guide/lieux/quais-de-bordeaux.webp",
    alt: "Les quais de la Garonne, promenade face aux façades du quai Richelieu",
    credit: "Zairon, CC BY-SA 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bordeaux_Quai_Richelieu_04.jpg",
  },
  "quartier-saint-pierre": {
    src: "/guide/lieux/quartier-saint-pierre.webp",
    alt: "La place du Parlement et ses terrasses",
    credit: "Marc Ryckaert (MJJR), CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bordeaux_Place_du_Parlement_R01.jpg",
  },
  "rocher-de-palmer": {
    src: "/guide/lieux/rocher-de-palmer.webp",
    alt: "Intérieur du Rocher de Palmer, à Cenon",
    credit: "Christophe Durand, CC BY-SA 2.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Int%C3%A9rieur_du_Rocher_de_Palmer_%C3%A0_Cenon.jpg",
  },
  "rue-sainte-catherine": {
    src: "/guide/lieux/rue-sainte-catherine.webp",
    alt: "La rue Sainte-Catherine, rue piétonne commerçante",
    credit: "Flyer84 at English Wikipedia, domaine public, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Rue_Sainte-Catherine_(Bordeaux)_2005.JPG",
  },
  "saint-emilion": {
    src: "/guide/lieux/saint-emilion.webp",
    alt: "Les toits de Saint-Émilion et son clocher",
    credit: "Hiroleo, CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Saint-%C3%89milion_en_2014.JPG",
  },
  "smith-haut-lafitte": {
    src: "/guide/lieux/smith-haut-lafitte.webp",
    alt: "La tour du château Smith Haut Lafitte",
    credit: "Elfabriciodelamancha, CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ch%C3%A2teau_Smith_Haut_Lafitte_2007.JPG",
  },
  "soulac-sur-mer": {
    src: "/guide/lieux/soulac-sur-mer.webp",
    alt: "Une villa typique de Soulac-sur-Mer",
    credit: "Renhour48, CC0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Soulac-sur-Mer_-_Villa_typique_C.jpg",
  },
  "theatre-femina": {
    src: "/guide/lieux/theatre-femina.webp",
    alt: "La façade du théâtre Femina",
    credit: "Pymouss, CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bordeaux_-_Th%C3%A9%C3%A2tre_Femina.jpg",
  },
  "tour-pey-berland": {
    src: "/guide/lieux/tour-pey-berland.webp",
    alt: "La tour Pey-Berland, clocher de la cathédrale",
    credit: "Jean-Christophe BENOIST, CC BY 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bordeaux_-_Tour_Pey-Berland.jpg",
  },
  "triangle-d-or": {
    src: "/guide/lieux/triangle-d-or.webp",
    alt: "Façades en pierre blonde du cours de l’Intendance",
    credit: "AlineRockstud68, CC BY-SA 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cours_de_l%27Intendance,Bordeaux,Gironde,France.jpg",
  },
  "village-notre-dame": {
    src: "/guide/lieux/village-notre-dame.webp",
    alt: "Une boutique d’antiquités rue Notre-Dame",
    credit: "Ardfern, CC BY-SA 3.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Le_Passage_Notre_Dame,_Bordeaux,_July_2014_(01).JPG",
  },
  "zoo-de-pessac": {
    src: "/guide/lieux/zoo-de-pessac.webp",
    alt: "Des makis cattas au zoo de Bordeaux Pessac",
    credit: "ZooBdxPessac, CC BY-SA 4.0, via Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Makis_Cattas_-_cr%C3%A9dit_Zoo_bordeaux_Pessac.jpg",
  },
};
